Fix "Uncaught TypeError: html.replace is not a function"
For a file drop action instead of an html string,  a `DataTransfer` object is given:
* this happens for a form were the drop-zone is the whole form and in the form there is a `contenteditable` element
* the user does a copy-paste inside that `contenteditable`
* using ckeditor to manage the `contenteditable`: http://docs.ckeditor.com/#!/api/CKEDITOR.plugins.clipboard.dataTransfer